# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  database:
    :password: password
  secret_key_base: 02573041f4247eb4c611ea1ecc5b0c7801f836d0a85883b09d37415fe4f0595ac370ba27dc78742509a397ce93614acee8fd7648108f1a4d248afb45114d939a

test:
  database:
    :password: password
 secret_key_base: 99f0f9387f22c094fc99845d55fd9cd613dbeb6adff96be492fbc3b036f0a9486052cc39d045a20a5b76980f302f854e0c3d14e9e7414aa06546636c8821462e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  database:
  :password: <%=ENV["PRODUCTION_DATABASE_PASSWORD"]%>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
